# Generated by Django 6.0 on 2025-12-31 05:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(db_index=True, help_text='Unique room identifier', max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('presidential', 'Presidential Suite')], db_index=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Rate per hour', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Rate per day (24 hours)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('floor', models.PositiveIntegerField(blank=True, help_text='Floor number', null=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities (WiFi, TV, AC, etc.)')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], db_index=True, default='available', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['room_number'],
                'indexes': [models.Index(fields=['room_type', 'status'], name='rooms_room_room_ty_d3390e_idx'), models.Index(fields=['status', 'room_number'], name='rooms_room_status_715794_idx')],
            },
        ),
    ]
